version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cbapp
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cbapp_db
    ports:
      - "5432:5432"

  nest-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://cbapp:admin@192.168.1.3:5432/cbapp_db"
